export const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const arrow=(diagonal=false)=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="${diagonal?'M6 18 18 6M6 6h12v12':'M4 12h15m-6-6 6 6-6 6'}" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
export function components({basePath='',site,siteUrl=''}) {
 const href=p=>`${basePath}${p}`;
 const button=(label,url='/contact/',light=false)=>`<a class="button${light?' button-light':''}" href="${href(url)}">${label}${arrow()}</a>`;
 const textLink=(label,url)=>`<a class="text-link" href="${href(url)}">${label}${arrow()}</a>`;
 const tags=items=>`<ul class="tags" aria-label="Направления работы">${items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`;
 const screen=(name='raznye-desktop.webp',alt='Главный экран сайта «Разные люди»',eager=false)=>`<div class="browser-screen"><div class="browser-bar" aria-hidden="true"><i></i><i></i><i></i><span>Разные люди</span></div><img src="${href(`/assets/img/${name}`)}" alt="${alt}" width="1440" height="1000" ${eager?'fetchpriority="high"':'loading="lazy"'}></div>`;
 const nav=[['Работы','/projects/'],['Услуги','/services/'],['Как работаю','/process/'],['Контакты','/contact/']];
 const header=route=>`<header class="header"><div class="container header-inner"><a class="brand" href="${href('/')}" aria-label="Сергей Авдеев, главная"><span class="monogram">са<span>.</span></span><span class="brand-name">Сергей Авдеев<span>Веб-разработчик</span></span></a><nav id="navigation" class="navigation" data-shell-nav aria-label="Основная навигация">${nav.map(([label,url])=>`<a href="${href(url)}" ${route===url||route.startsWith('/work/')&&url==='/projects/'||route==='/works/'&&url==='/projects/'?'aria-current="page"':''}>${label}</a>`).join('')}<a class="button nav-cta" href="${href('/contact/')}">Обсудить проект${arrow()}</a><div class="mobile-nav-note">Сергей Авдеев<br>Сайты и веб-приложения</div></nav><button class="menu-toggle" data-menu-toggle aria-label="Открыть меню" aria-controls="navigation" aria-expanded="false"><span></span><span></span></button></div></header>`;
 const footer=()=>`<footer class="footer container"><a class="brand" href="${href('/')}" aria-label="На главную"><span class="monogram">са<span>.</span></span><span>Сергей Авдеев<br><small>Сайты и веб-приложения</small></span></a><div class="footer-links">${nav.map(([l,u])=>`<a href="${href(u)}">${l}</a>`).join('')}</div><a href="${esc(site.github)}" target="_blank" rel="noopener">GitHub ${arrow(true)}</a><small>© ${new Date().getUTCFullYear()}</small></footer>`;
 const cta=()=>`<section class="container final-cta"><div><span class="section-label">Есть задача?</span><h2>Обсудим ваш<br>проект<span class="accent">?</span></h2><p>Расскажите, что хотите сделать.<br>Начать можно без готового технического задания.</p></div><div class="cta-action">${button('Обсудить проект','/contact/',true)}<span>Сайт · Веб-приложение · Доработка</span></div><span class="cta-mark" aria-hidden="true">↗</span></section>`;
 const doc=(route,title,description,body)=>`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)} — Сергей Авдеев</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${process.env.PREVIEW==='1'?'noindex,nofollow':'index,follow'}"><meta name="theme-color" content="#F5F3EE"><meta name="app-base" content="${esc(basePath)}">${siteUrl?`<link rel="canonical" href="${esc(siteUrl+route)}">`:''}<meta property="og:title" content="${esc(title)} — Сергей Авдеев"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="${siteUrl||basePath}/og-image.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${href('/favicon.svg')}"><link rel="manifest" href="${href('/site.webmanifest')}"><link rel="preload" as="font" type="font/woff2" href="${href('/assets/fonts/manrope-cyrillic.woff2')}" crossorigin><link rel="stylesheet" href="${href('/assets/css/editorial.css')}"></head><body class="editorial"><a class="skip-link" href="#main">К содержанию</a>${header(route)}<main id="main">${body}</main>${footer()}<script type="module" src="${href('/assets/js/main.js')}"></script></body></html>`;
 return {href,button,textLink,tags,screen,cta,doc};
}
