import { components, esc, arrow } from './components.mjs';
import { services, steps } from './content.mjs';
export function createEditorial(options){
 const {projects,site}=options, p=projects[0];
 const {href,button,textLink,tags,screen,cta,doc}=components(options);
 const featured=()=>`<article class="featured-project"><a class="featured-visual" href="${href(`/work/${p.slug}/`)}" aria-label="Смотреть кейс «${esc(p.title)}»"><span class="visual-label">Личный проект / ${p.year}</span>${screen('raznye-desktop.webp','Рабочий интерфейс сайта «Разные люди»')}<span class="visual-open">Смотреть кейс${arrow(true)}</span></a><div class="project-caption"><div><span class="section-label">${esc(p.type)}</span><h3><a href="${href(`/work/${p.slug}/`)}">${esc(p.title)}${arrow(true)}</a></h3></div><p>${esc(p.shortDescription)}</p><div>${tags(['Дизайн','Frontend','Motion'])}</div></div></article>`;
 const experiments=()=>`<div class="experiment-heading"><h3>В работе и экспериментах</h3><p>Прототипы и интерактивные механики. Не клиентские кейсы.</p></div><div class="experiment-grid"><a class="experiment-card" href="${href('/demo/operations-os/')}"><div class="experiment-visual ops-visual"><span class="experiment-badge">Эксперимент</span><img src="${href('/assets/img/operations-desktop.webp')}" alt="Интерактивный прототип Operations OS" width="1440" height="1000" loading="lazy"></div><div class="experiment-caption"><div><span class="section-label">Прототип веб-приложения</span><h3>Operations OS</h3><p>Интерфейс управления аутсорсингом.<br>Можно открыть и попробовать.</p></div>${arrow(true)}</div></a><a class="experiment-card" href="${href('/effects/kinetic-type/')}"><div class="experiment-visual type-visual"><span class="experiment-badge">Эксперимент</span><span class="type-art" aria-hidden="true">ДВИЖЕНИЕ<br><span>МЕНЯЕТ</span><br>СМЫСЛ<span class="type-period">.</span></span><span class="type-annotation">Типографика × взаимодействие</span></div><div class="experiment-caption"><div><span class="section-label">Интерактивная механика</span><h3>Типографика в движении</h3><p>Текст становится частью<br>пользовательского взаимодействия.</p></div>${arrow(true)}</div></a></div>`;
 const serviceRows=()=>`<div class="service-rows">${services.map((s,i)=>`<a href="${href('/services/')}" class="service-row"><span class="row-number">0${i+1}</span><h3>${s.title}</h3><p>${s.short}</p>${arrow(true)}</a>`).join('')}</div>`;
 const processRows=(full=false)=>`<div class="process-rows ${full?'process-full':''}">${steps.map(([title,desc,result],i)=>`<article class="process-row"><span class="row-number">0${i+1}</span><div><h${full?'2':'3'}>${title}</h${full?'2':'3'}>${full?`<p>${desc}</p>`:''}</div><div class="process-result">${full?'<span class="section-label">Результат этапа</span>':''}<p>${full?result:desc}</p></div></article>`).join('')}</div>`;
 function home(){return doc('/','Создаю сайты и веб-приложения для бизнеса',site.description,`<section class="container home-hero"><div class="hero-copy"><p class="intro-label"><span></span>Независимый веб-разработчик</p><h1>Создаю сайты<br>и веб-приложения<br>для бизнеса<span class="accent">.</span></h1><p class="hero-description">От структуры и дизайна до разработки и запуска. Помогаю превратить задачу в понятный, работающий продукт.</p><div class="actions">${button('Обсудить проект')}${textLink('Смотреть работы','/projects/')}</div><div class="hero-footnote"><span>Работа напрямую со мной</span><span>От идеи до запуска</span></div></div><a href="${href(`/work/${p.slug}/`)}" class="hero-art" aria-label="Открыть кейс «Разные люди»"><div class="hero-art-heading"><span>Проект в фокусе</span>${arrow(true)}</div><div class="hero-device">${screen('raznye-desktop.webp','Первый экран сайта «Разные люди»',true)}<div class="device-base"></div></div><div class="hero-art-caption"><strong>Разные люди</strong><span>Сайт страйкбольной команды</span><span class="hero-art-tags">Дизайн / Разработка / Motion</span></div><span class="hero-art-index" aria-hidden="true">01</span></a></section>
 <section class="container section selected-work"><div class="section-heading"><div><span class="section-label">Избранная работа</span><h2>Проект, который<br>можно открыть.</h2></div>${textLink('Все работы','/projects/')}</div>${featured()}${experiments()}</section>
 <section class="value-section"><div class="container value-grid"><div><span class="section-label">Подход к работе</span><h2>Сначала задача.<br>Затем интерфейс<br>и код.</h2></div><div class="value-copy"><p class="large-copy">Продумываю не только то, как сайт выглядит, но и то, как человек им пользуется.</p><div class="value-points"><article><h3>Целостный проект</h3><p>Структура, дизайн и разработка связаны одной задачей.</p></article><article><h3>Понятные решения</h3><p>Объясняю выбор и согласую ключевые этапы до запуска.</p></article><article><h3>Работа в браузере</h3><p>Показываю действующий интерфейс, который можно проверить.</p></article><article><h3>Внимание к деталям</h3><p>Проверяю адаптив, навигацию, формы и состояния элементов.</p></article></div></div></div></section>
 <section class="container section"><div class="section-heading"><div><span class="section-label">Услуги</span><h2>Что нужно<br>вашему проекту?</h2></div>${textLink('Об услугах','/services/')}</div>${serviceRows()}</section>
 <section class="container section process-preview"><div class="section-heading"><div><span class="section-label">Как работаю</span><h2>Понятно на каждом этапе.</h2></div>${textLink('Весь процесс','/process/')}</div>${processRows()}</section>${cta()}`)}
 function works(route='/projects/'){return doc(route,'Работы','Реальные проекты и явно обозначенные эксперименты Сергея Авдеева.',`<section class="container page-hero"><span class="section-label">Работы</span><div class="page-hero-grid"><h1>Реальные задачи.<br>Рабочие решения.</h1><p>Здесь можно посмотреть, что было сделано, изучить интерфейс и открыть рабочую версию.</p></div></section><section class="container work-list">${featured()}${experiments()}</section>${cta()}`)}
 function casePage(project){const info=project.caseStudy;return doc(`/work/${project.slug}/`,`${project.title} · кейс`,project.shortDescription,`<section class="container case-intro"><a class="back-link" href="${href('/projects/')}">← Все работы</a><div class="case-intro-grid"><div><span class="section-label">${esc(project.type)} / Личный проект / ${project.year}</span><h1>${esc(project.title)}<span class="accent">.</span></h1><p class="large-copy">${esc(project.shortDescription)}</p>${tags(project.services)}<div class="actions">${button('Открыть сайт',project.demoRoute)}<a class="text-link" href="#result">Что сделано${arrow()}</a></div></div><div class="case-intro-note"><span>Сайт команды</span><p>Характер.<br>Участие.<br>Следующий шаг.</p></div></div></section><section class="case-hero-visual container">${screen('raznye-desktop.webp','Полный первый экран сайта «Разные люди»',true)}</section>
 <section class="container section case-context"><article><span class="row-number">01 / Задача</span><h2>Передать характер.<br>Объяснить участие.</h2><p>${esc(info.task)}</p></article><article><span class="row-number">02 / Решение</span><h2>От первого впечатления<br>до заявки.</h2><p>${esc(info.solution)}</p></article></section>
 <section class="case-video-section"><div class="container"><div class="section-heading"><div><span class="section-label">Визуальная система</span><h2>В центре внимания<br>сама команда.</h2></div><p>Реальные материалы проекта,<br>единая атмосфера и сдержанный интерфейс.</p></div><video controls playsinline preload="none" poster="${href('/projects/raznye-ludi/assets/scene_01.webp')}" aria-label="Видео главного экрана проекта «Разные люди»"><source src="${href('/projects/raznye-ludi/assets/final_hero.mp4')}" type="video/mp4"></video><p class="media-caption">Видео из главной сцены проекта. Воспроизведение по нажатию.</p></div></section>
 <section id="result" class="container section delivered"><div><span class="section-label">Работа над проектом</span><h2>От структуры<br>до публикации.</h2><p>Сначала пользовательский маршрут, затем визуальная система, разработка и проверка.</p></div><ol>${info.done.map((d,i)=>`<li><span>0${i+1}</span>${esc(d)}</li>`).join('')}</ol></section>
 <section class="container case-detail-visual"><div class="section-heading"><div><span class="section-label">Рабочий интерфейс</span><h2>История продолжается<br>при прокрутке.</h2></div>${textLink('Попробовать сайт',project.demoRoute)}</div>${screen('raznye-detail.webp','Раздел сайта «Разные люди» при прокрутке')}</section>
 <section class="container section adaptive-section"><div class="adaptive-copy"><span class="section-label">Адаптивная версия</span><h2>Тот же характер.<br>Другой экран.</h2><p>На телефоне меняются композиция, размер текста и навигация. Главный сценарий остаётся доступен одним касанием.</p>${textLink('Открыть рабочую версию',project.demoRoute)}</div><div class="mobile-proofs"><figure class="phone"><img src="${href('/assets/img/raznye-mobile.webp')}" alt="Главный экран «Разные люди» на телефоне" width="390" height="844" loading="lazy"></figure><figure class="phone phone-offset"><img src="${href('/assets/img/raznye-mobile-detail.webp')}" alt="Раздел сайта «Разные люди» на телефоне" width="390" height="844" loading="lazy"></figure></div></section>${cta()}`)}
 function servicesPage(){return doc('/services/','Услуги','Сайты для бизнеса, веб-приложения, развитие и поддержка.',`<section class="container page-hero"><span class="section-label">Услуги</span><div class="page-hero-grid"><h1>Веб-разработка<br>для ваших задач.</h1><p>Запустить сайт, собрать внутренний инструмент или доработать существующий продукт.</p></div></section><section class="container services-grid">${services.map((s,i)=>`<article class="service-detail"><div class="service-card-top"><span class="row-number">0${i+1}</span>${arrow(true)}</div><h2>${s.title}</h2><p class="service-summary">${s.short}</p>${tags(s.tags)}<dl><div><dt>Кому подходит</dt><dd>${s.for}</dd></div><div><dt>Что входит</dt><dd>${s.includes}</dd></div><div><dt>Что получаете</dt><dd>${s.result}</dd></div></dl>${textLink('Обсудить задачу','/contact/')}</article>`).join('')}</section><section class="container scope-note"><h2>Состав работы зависит<br>от задачи.</h2><p>Определяем необходимые страницы и функции до разработки. Сроки и стоимость обсуждаем после знакомства с проектом.</p></section>${cta()}`)}
 function process(){return doc('/process/','Как работаю','Пять этапов работы над сайтом: от первого обсуждения до поддержки.',`<section class="container page-hero"><span class="section-label">Как работаю</span><div class="page-hero-grid"><h1>От первого разговора<br>до рабочего сайта.</h1><p>Вы знаете, на каком этапе проект, что нужно согласовать и какой результат будет дальше.</p></div></section><section class="container process-page">${processRows(true)}</section><section class="container starting-note"><span class="row-number">Для начала</span><h2>Не обязательно<br>приходить с ТЗ.</h2><p>Достаточно описать задачу своими словами. Если есть текущий сайт, примеры или макет, они помогут быстрее определить направление.</p></section>${cta()}`)}
 function contact(){const channels=site.contacts.filter(c=>c.kind!=='github');return doc('/contact/','Обсудим ваш проект?','Подготовить обращение Сергею Авдееву по поводу сайта или веб-приложения.',`<section class="container contact-layout"><div class="contact-intro"><span class="section-label">Контакты</span><h1>Обсудим<br>ваш проект<span class="accent">?</span></h1><p class="large-copy">Расскажите о задаче. Что нужно сделать, для кого и какой результат вы хотите получить.</p><div class="contact-channels">${channels.map(c=>`<a href="${esc(c.href)}"><div><strong>${esc(c.label)}</strong></div>${arrow(true)}</a>`).join('')}<a href="${esc(site.github)}" target="_blank" rel="noopener"><div><strong>GitHub</strong><span>Профиль разработчика и исходный код</span></div>${arrow(true)}</a></div><div class="contact-signature"><span class="monogram">са<span>.</span></span><p>Сергей Авдеев<br><span>Веб-разработчик</span></p></div></div><div class="contact-form-panel"><span class="section-label">Коротко о задаче</span><h2>Начнём с деталей.</h2><p class="form-note">${channels.length?'Заполните поля, чтобы подготовить обращение.':'Прямой канал связи пока не указан. Можно подготовить и скопировать текст обращения. Эта форма не отправляет сообщения.'}</p><form data-contact-form><label>Имя<input name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="100"></label><label>Telegram или email<input name="contact" autocomplete="email" placeholder="Ваш контакт для ответа" required maxlength="200"></label><label>Коротко о задаче<textarea name="message" rows="4" placeholder="Что вы хотите создать или изменить?" required maxlength="5000"></textarea></label><button class="button" type="submit">Подготовить сообщение${arrow()}</button></form><div data-contact-result role="status" aria-live="polite" hidden></div><button class="text-link" type="button" data-contact-copy hidden>Скопировать текст${arrow()}</button><p class="privacy-note">Введённые данные остаются в этой вкладке.</p></div></section>`)}
 return {home,works,casePage,services:servicesPage,process,contact};
}
