import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createV7Renderer} from './v7-render.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'dist');
const basePath=(process.env.BASE_PATH||'').trim().replace(/\/+$/,'');
const siteUrl=(process.env.SITE_URL||'').trim().replace(/\/$/,'');
if(basePath&&!basePath.startsWith('/')) throw new Error('BASE_PATH must start with /');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const copy=(src,dst)=>{if(!fs.existsSync(src))return;fs.mkdirSync(path.dirname(dst),{recursive:true});fs.cpSync(src,dst,{recursive:true});};
copy(path.join(root,'public'),out);copy(path.join(root,'.build'),path.join(out,'assets','js'));
const r=createV7Renderer({basePath,siteUrl});
const write=(route,html)=>{const dir=route==='/'?out:path.join(out,route.replace(/^\//,'').replace(/\/$/,''));fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);};
write('/',r.home());write('/works/',r.works());write('/work/raznye-ludi/',r.caseRaznye());write('/work/operations-os/',r.caseOperations());write('/about/',r.about());write('/contact/',r.contact());write('/services/',r.legacy('Услуги','services'));write('/process/',r.legacy('Как я работаю','process'));fs.writeFileSync(path.join(out,'404.html'),r.notFound());fs.writeFileSync(path.join(out,'.nojekyll'),'');
const publicBase=siteUrl||'https://avdeevgreyfog-cmd.github.io/sergey-portfolio';
const routes=['/','/works/','/work/raznye-ludi/','/work/operations-os/','/about/','/contact/'];
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: ${basePath}/demo/\nSitemap: ${publicBase}/sitemap.xml\n`);
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(route=>`<url><loc>${publicBase}${route}</loc></url>`).join('')}</urlset>`);
console.log(`Portfolio V7 built: ${routes.length} indexed routes.`);
