const menu=document.querySelector<HTMLButtonElement>('[data-menu-toggle]');
const nav=document.querySelector<HTMLElement>('[data-shell-nav]');
const closeMenu=()=>{nav?.classList.remove('is-open');menu?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};
menu?.addEventListener('click',()=>{const open=!nav?.classList.contains('is-open');nav?.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
document.addEventListener('keydown',(e)=>{if(e.key==='Escape')closeMenu()});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const filters=[...document.querySelectorAll<HTMLButtonElement>('[data-filter]')];const cards=[...document.querySelectorAll<HTMLElement>('[data-project-category]')];const empty=document.querySelector<HTMLElement>('[data-work-empty]');filters.forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter||'Все';filters.forEach(b=>{const active=b===button;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',String(active))});let visible=0;cards.forEach(card=>{const show=filter==='Все'||card.dataset.projectCategory===filter;card.hidden=!show;if(show)visible++});if(empty)empty.hidden=visible>0;}));
const form=document.querySelector<HTMLFormElement>('[data-contact-form]');form?.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const result=document.querySelector<HTMLElement>('[data-contact-result]');if(result){const data=new FormData(form);const body=`Имя: ${data.get('name')}\nКонтакт: ${data.get('contact')}\nТип проекта: ${data.get('type')}\n\n${data.get('message')||''}`;const link=result.querySelector<HTMLAnchorElement>('[data-email-draft]');if(link)link.href=`mailto:avdeevgreyfog@gmail.com?subject=${encodeURIComponent('Обсуждение проекта: '+data.get('type'))}&body=${encodeURIComponent(body)}`;result.hidden=false;}});
// Keep the closed mobile navigation out of keyboard focus.
const mobile=matchMedia("(max-width: 760px)");
const syncMenu=()=>{if(nav)nav.inert=mobile.matches&&!nav.classList.contains("is-open")};
new MutationObserver(syncMenu).observe(nav!,{attributes:true,attributeFilter:["class"]});mobile.addEventListener("change",()=>{closeMenu();syncMenu()});syncMenu();
