export const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function core({basePath='',siteUrl=''}){
 const href=(p='/')=>`${basePath}${p.startsWith('/')?p:`/${p}`}`||'/';
 const abs=p=>siteUrl?`${siteUrl.replace(/\/$/,'')}${p}`:href(p);
 const nav=[['Главная','/'],['Работы','/works/'],['Обо мне','/about/'],['Контакты','/contact/']];
 const header=current=>`<header class="hdr"><div class="shell hdr-in"><a class="logo" href="${href('/')}">SA</a><nav class="nav" data-shell-nav>${nav.map(([n,p])=>`<a href="${href(p)}"${current===p?' aria-current="page"':''}>${n}</a>`).join('')}<a class="nav-cta" href="${href('/contact/')}">Обсудить проект →</a></nav><button class="menu" data-menu-toggle aria-expanded="false" aria-label="Меню"><i></i><i></i></button></div></header>`;
 const footer=()=>`<footer class="ftr"><div class="shell ftr-top"><b class="logo">SA</b><div><strong>Сергей Авдеев</strong><small>Веб-разработка</small></div><nav>${nav.map(([n,p])=>`<a href="${href(p)}">${n}</a>`).join('')}</nav><a href="https://github.com/avdeevgreyfog-cmd" target="_blank" rel="noreferrer">GitHub ↗</a></div><div class="shell ftr-bot"><span>© ${new Date().getUTCFullYear()} Сергей Авдеев</span><span>Цифровые продукты, которые работают.</span><a href="#top">Наверх ↑</a></div></footer>`;
 const orb=(small='')=>`<div class="orb ${small}" aria-hidden="true"><i></i><i></i><b></b></div>`;
 const doc=({route,title,desc,body,current=route,robots='index,follow'})=>`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="${robots}"><meta name="theme-color" content="#050b14"><meta name="app-base" content="${esc(basePath)}"><link rel="canonical" href="${abs(route)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:image" content="${abs('/og-image.png')}"><link rel="icon" href="${href('/favicon.svg')}"><link rel="stylesheet" href="${href('/assets/css/v7-base.css')}"><link rel="stylesheet" href="${href('/assets/css/v7-pages.css')}"><link rel="stylesheet" href="${href('/assets/css/v7-responsive.css')}"></head><body id="top"><a class="skip" href="#main">К содержанию</a>${header(current)}${body}${footer()}<script type="module" src="${href('/assets/js/v7-main.js')}"></script></body></html>`;
 const cta=()=>`<section class="cta"><div class="shell cta-box"><div><span class="k">Готовы обсудить проект?</span><h2>Давайте создадим<br>что-то полезное вместе</h2></div><p>Расскажите о задаче — начнём с понятного следующего шага.</p><a class="btn light" href="${href('/contact/')}">Обсудить проект →</a></div></section>`;
 const feature=(t,p,i='01')=>`<article class="feature" data-reveal><span>${i}</span><h3>${t}</h3><p>${p}</p></article>`;
 const browser=inner=>`<div class="browser"><div class="browser-top"><i></i><i></i><i></i><span>project preview</span></div>${inner}</div>`;
 return{href,doc,cta,feature,browser,orb};
}
